name: Ci

on:
    workflow_dispatch:
    push:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
          contents: write

        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Get gbdk
              run: |
                wget https://github.com/gbdk-2020/gbdk-2020/releases/download/4.4.0/gbdk-linux64.tar.gz
                tar -xzf gbdk-linux64.tar.gz

            - name: Build
              run: |
                make -j GBDK_HOME=gbdk/

            - name: Rename rom
              run: |
                mv `find obj/ -type f -name '*.gb'` "$(date +"%d-%m-%y %k-%M-%S").gb"

            - name: Get current date
              id: date
              run: echo "::set-output name=date::$(date +"%d-%m-%y %k-%M-%S")"
  
            - name: Deploy
              uses: ncipollo/release-action@v1
              with:
                artifacts: "*.gb"
                tag: ${{ steps.date.outputs.date }}
